name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']
        laravel: ['10.10.1', '10.48', '11.0']
        exclude:
          - php: '8.1'
            laravel: '11.0'
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Lock Package Versions
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}.*" --no-update -v && composer require "illuminate/database:${{ matrix.laravel }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Run Tests [sqlite]
        run: php vendor/bin/phpunit --stop-on-error --display-errors
        env:
          TEST_DB_ENGINE: sqlite
      - name: Run Tests [mysql 5.7]
        run: php vendor/bin/phpunit --stop-on-error --display-errors
        env:
          TEST_DB_ENGINE: mysql
          TEST_DB_PORT: ${{ job.services.mysql57.ports[3306] }}
      - name: Run Tests [mysql 8.2]
        run: php vendor/bin/phpunit --stop-on-error --display-errors
        env:
          TEST_DB_ENGINE: mysql
          TEST_DB_PORT: ${{ job.services.mysql82.ports[3306] }}
      - name: Run Tests [postgres 12]
        run: php vendor/bin/phpunit --stop-on-error --display-errors
        env:
          TEST_DB_ENGINE: pgsql
          TEST_DB_PORT: ${{ job.services.postgres12.ports[5432] }}
          TEST_DB_PASSWORD: postgres
      - name: Run Tests [postgres 16]
        run: php vendor/bin/phpunit --stop-on-error --display-errors
        env:
          TEST_DB_ENGINE: pgsql
          TEST_DB_PORT: ${{ job.services.postgres16.ports[5432] }}
          TEST_DB_PASSWORD: postgres
    services:
      mysql57:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: history_test
        ports:
          - 3306
      mysql82:
        image: mysql:8.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: history_test
        ports:
          - 3306
      postgres16:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: history_test
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres12:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: history_test
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
